cicd: github
settings:
  cosmos_name: xia-cosmos
  realm_name: protocol
  foundation_name: xia-framework
  application_name: xia-demo-framework-01
environments:
  dev:
    match_branch: refs/heads/main
    stages:
    - deploy
    - local-test
  sit:
    match_branch: refs/tags/.*
    stages:
    - remote-test
  prd:
    match_branch: refs/tags/.*
    match_event: release
    stages:
    - publish
