xia-module:
  package: xia-module
  class: Module
module-state-gcs:
  package: xia-module-terraform-gcs
  class: GcsState
  events:
    deploy:
gcp-module-dataset:
  package: xia-module-gcp-bigquery
  class: Dataset
  events:
    deploy:
