name: Workflow - sit

on:
  push:
    tags:
    - '*'

jobs:
  remote-test:
    if: false
    environment: sit
    runs-on: ubuntu-latest
    steps:
    - id: checkout-code
      uses: actions/checkout@v4
